---
kind: pipeline
name: compliance
type: docker

steps:
    -   name: linter
        image: node:16-alpine
        pull: always
        commands:
            - yarn --frozen-lockfile --non-interactive
            - yarn lint
            - yarn build

trigger:
    ref:
        - refs/heads/master
        - refs/pull/**
        - refs/tags/**
    event:
        exclude:
            - promote
---
kind: pipeline
name: tests
type: docker

steps:
    -   name: tests
        image: node:16-alpine
        pull: always
        commands:
            - yarn --frozen-lockfile --non-interactive
            - yarn test

trigger:
    ref:
        - refs/heads/master
        - refs/pull/**
        - refs/tags/**
    event:
        exclude:
            - promote
---
kind: pipeline
name: docker
type: docker

platform:
    arch: amd64

steps:
    -   name: build
        image: plugins/docker
        pull: always
        privileged: true
        environment:
            DOCKER_REGISTRY:
                from_secret: docker_registry
        settings:
            username:
                from_secret: docker_username
            password:
                from_secret: docker_password
            tags:
                - "${DRONE_DEPLOY_TO}"
        commands:
            - export PLUGIN_REPO=$DOCKER_REGISTRY/kana
            - /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker

trigger:
    event:
        - promote