kind: pipeline
name: node-v10
type: docker

steps:
    -   name: install
        image: node:10
        commands:
            - node -v
            - npm -v
            - npm i --no-save --quiet --no-optional --no-audit
    -   name: tests
        image: node:10
        commands:
            - npm run test
    -   name: linter
        image: node:10
        commands:
            - npm run lint

---
kind: pipeline
name: node-v12
type: docker

steps:
    -   name: install
        image: node:12
        commands:
            - node -v
            - npm -v
            - npm i --no-save --quiet --no-optional --no-audit
    -   name: tests
        image: node:12
        commands:
            - npm run test
    -   name: linter
        image: node:12
        commands:
            - npm run lint

---
kind: pipeline
name: deps
type: docker

steps:
    -   name: install
        image: node:12
        commands:
            - node -v
            - npm -v
            - npm i --no-save --quiet --no-optional --no-audit
        depends_on: [ clone ]
    -   name: audit
        image: node:12
        commands:
            - npm audit
        depends_on: [ clone ]
    -   name: outdated
        image: node:12
        commands:
            - npm run check-outdated
        depends_on: [ install ]
