kind: pipeline
name: compliance
type: docker

steps:
    -   name: linter
        image: node:12-alpine
        commands:
            - yarn --frozen-lockfile --non-interactive
            - yarn lint

trigger:
    event:
        exclude:
            - promote

---
kind: pipeline
name: tests
type: docker

steps:
    -   name: tests
        image: node:12-alpine
        commands:
            - yarn --frozen-lockfile --non-interactive
            - yarn test

trigger:
    event:
        exclude:
            - promote

---
kind: pipeline
name: docker
type: docker

steps:
    -   name: build
        image: plugins/docker
        privileged: true
        environment:
            DOCKER_REGISTRY:
                from_secret: docker_registry
        settings:
            username:
                from_secret: docker_username
            password:
                from_secret: docker_password
            tags:
                - "${DRONE_DEPLOY_TO}"
        commands:
            - export PLUGIN_REPO=$DOCKER_REGISTRY/kana
            - /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker

trigger:
    event:
        - promote

---
kind: pipeline
name: artifacts
type: docker

steps:
    -   name: collect
        image: node:12-alpine
        commands:
            - yarn --frozen-lockfile --non-interactive --production
    -   name: upload
        image: plugins/s3-cache
        settings:
            rebuild: true
            path: artifacts/${DRONE_REPO_NAME}/${DRONE_COMMIT}/
            mount:
                - node_modules
            access_key:
                from_secret: aws_access_key_id
            secret_key:
                from_secret: aws_secret_access_key
            endpoint:
                from_secret: aws_endpoint
    -   name: flush
        image: plugins/s3-cache
        settings:
            flush: true
            flush_age: 7
            flush_path: artifacts/${DRONE_REPO_NAME}/
            access_key:
                from_secret: aws_access_key_id
            secret_key:
                from_secret: aws_secret_access_key
            endpoint:
                from_secret: aws_endpoint

trigger:
    event:
        - promote
    target:
        - production
