kind: pipeline
name: node-v10
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: tests
        image: node:10
        commands:
            - npm i --no-save --quiet --no-optional
            - npm run test
    -   name: linter
        image: node:10
        commands:
            - npm run lint
trigger:
    branch:
        - master
        - drone

---
kind: pipeline
name: node-v12
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: tests
        image: node:12
        commands:
            - npm i --no-save --quiet --no-optional
            - npm run test
    -   name: linter
        image: node:12
        commands:
            - npm run lint

trigger:
    branch:
        - master
        - drone
