kind: pipeline
name: node-v10
type: docker

steps:
    -   name: restore-cache
        image: meltwater/drone-cache
        failure: ignore
        environment:
            AWS_ACCESS_KEY_ID:
                from_secret: aws_access_key_id
            AWS_SECRET_ACCESS_KEY:
                from_secret: aws_secret_access_key
            PLUGIN_PATH_STYLE: true
        settings:
            endpoint:
                from_secret: aws_endpoint
            region: ab-1
            bucket: drone-cache
            restore: true
            cache_key: '{{ .Commit.Branch }}-v10'
            archive_format: gzip
            mount:
                - ./node_modules
        depends_on: [ clone ]
    -   name: install
        image: node:10
        commands:
            - node -v
            - npm -v
            - npm i --no-save --quiet --no-optional --no-audit
        depends_on: [ restore-cache ]
    -   name: tests
        image: node:10
        commands:
            - npm run test
        depends_on: [ install ]
    -   name: linter
        image: node:10
        commands:
            - npm run lint
        depends_on: [ install ]
    -   name: rebuild-cache
        image: meltwater/drone-cache
        failure: ignore
        environment:
            AWS_ACCESS_KEY_ID:
                from_secret: aws_access_key_id
            AWS_SECRET_ACCESS_KEY:
                from_secret: aws_secret_access_key
            PLUGIN_PATH_STYLE: true
        settings:
            endpoint:
                from_secret: aws_endpoint
            region: ab-1
            bucket: drone-cache
            rebuild: true
            cache_key: '{{ .Commit.Branch }}-v10'
            archive_format: gzip
            mount:
                - ./node_modules
        depends_on: [ install ]

trigger:
    event:
        exclude:
            - cron

---
kind: pipeline
name: node-v12
type: docker

steps:
    -   name: restore-cache
        image: meltwater/drone-cache
        failure: ignore
        environment:
            AWS_ACCESS_KEY_ID:
                from_secret: aws_access_key_id
            AWS_SECRET_ACCESS_KEY:
                from_secret: aws_secret_access_key
            PLUGIN_PATH_STYLE: true
        settings:
            endpoint:
                from_secret: aws_endpoint
            region: ab-1
            bucket: drone-cache
            restore: true
            cache_key: '{{ .Commit.Branch }}-v12'
            archive_format: gzip
            mount:
                - ./node_modules
        depends_on: [ clone ]
    -   name: install
        image: node:12
        commands:
            - node -v
            - npm -v
            - npm i --no-save --quiet --no-optional --no-audit
        depends_on: [ restore-cache ]
    -   name: tests
        image: node:12
        commands:
            - npm run test
        depends_on: [ install ]
    -   name: linter
        image: node:12
        commands:
            - npm run lint
        depends_on: [ install ]
    -   name: rebuild-cache
        image: meltwater/drone-cache
        failure: ignore
        environment:
            AWS_ACCESS_KEY_ID:
                from_secret: aws_access_key_id
            AWS_SECRET_ACCESS_KEY:
                from_secret: aws_secret_access_key
            PLUGIN_PATH_STYLE: true
        settings:
            endpoint:
                from_secret: aws_endpoint
            region: ab-1
            bucket: drone-cache
            rebuild: true
            cache_key: '{{ .Commit.Branch }}-v12'
            archive_format: gzip
            mount:
                - ./node_modules
        depends_on: [ install ]

trigger:
    event:
        exclude:
            - cron

---
kind: pipeline
name: deps
type: docker

steps:
    -   name: restore-cache
        image: meltwater/drone-cache
        failure: ignore
        environment:
            AWS_ACCESS_KEY_ID:
                from_secret: aws_access_key_id
            AWS_SECRET_ACCESS_KEY:
                from_secret: aws_secret_access_key
            PLUGIN_PATH_STYLE: true
        settings:
            endpoint:
                from_secret: aws_endpoint
            region: ab-1
            bucket: drone-cache
            restore: true
            cache_key: '{{ .Commit.Branch }}-deps'
            archive_format: gzip
            mount:
                - ./node_modules
        depends_on: [ clone ]
    -   name: install
        image: node:12
        commands:
            - node -v
            - npm -v
            - npm i --no-save --quiet --no-optional --no-audit
        depends_on: [ restore-cache ]
    -   name: audit
        image: node:12
        commands:
            - npm audit
        depends_on: [ clone ]
    -   name: outdated
        image: node:12
        commands:
            - npm run check-outdated
        depends_on: [ install ]
    -   name: rebuild-cache
        image: meltwater/drone-cache
        failure: ignore
        environment:
            AWS_ACCESS_KEY_ID:
                from_secret: aws_access_key_id
            AWS_SECRET_ACCESS_KEY:
                from_secret: aws_secret_access_key
            PLUGIN_PATH_STYLE: true
        settings:
            endpoint:
                from_secret: aws_endpoint
            region: ab-1
            bucket: drone-cache
            rebuild: true
            cache_key: '{{ .Commit.Branch }}-deps'
            archive_format: gzip
            mount:
                - ./node_modules
        depends_on: [ install ]
