name: build

on:
    pull_request:
        branches:
            - master
        paths:
            - Dockerfile
        types: [ opened, synchronize, reopened ]

env:
    REGISTRY: ${{ vars.DOCKER_REGISTRY }}
    IMAGE_NAME: ${{ forge.repository }}

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            -   name: Checkout
                uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
                with:
                    fetch-depth: 0
                    fetch-tags: true
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
            -   name: Gather metadata
                id: meta
                uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            -   name: Build container
                uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
                with:
                    context: .
                    push: false
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}