name: compliance

on:
    pull_request:
        branches:
            - master
        types: [ opened, synchronize, reopened ]

jobs:
    linter:
        runs-on: ubuntu-24.04
        steps:
            -   name: Checkout
                uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
            -   name: Set up PNPM package manager
                uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
            -   name: Set up NodeJS
                uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
                with:
                    node-version: 22
                    cache: pnpm
            -   name: Install dependencies
                run: pnpm install
            -   name: Compile
                run: pnpm build
            -   name: ESLint
                run: pnpm lint:eslint
            -   name: Prettier
                run: pnpm lint:prettier