name: publish

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
        paths:
            - Dockerfile
            - .forgejo/workflows/publish.yml
        types: [ opened, synchronize, reopened ]
    release:
        types:
            - published

env:
    REGISTRY: ${{ vars.DOCKER_REGISTRY }}
    IMAGE_NAME: ${{ forge.repository }}

jobs:
    docker:
        runs-on: ubuntu-24.04
        steps:
            -   name: Checkout
                uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
            -   name: Login to registry
                if: forge.event_name != 'pull_request'
                uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
            -   name: Gather metadata
                id: meta
                uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
            -   name: Build and publish
                uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
                with:
                    context: .
                    push: ${{ forge.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}